feat: update libs and eslint/prettier rules (#179669)
tecsinapse/eslint-config pull request #11
Opened 2022-09-26 18:06 UTC by guilhermebrrrs

Alterações:
- Atualizada versões das dependências
- Alterada para versão fixa das dependências
- Atualizada regras para eslint/prettier

2022-09-26 18:06 UTC, gitTecsinapse commented
https://tecsinapse.tpondemand.com/entity/179669

2022-09-26 19:59 UTC, dennervidal requested changes

2022-09-26 19:59 UTC, dennervidal commented on package.json
>      "prettier": "2.0.5"
faltou atualizar o `prettier`
pode marcar essas dependencias com ~, já que esse repo não é algo que quebra diretamente nosso código, apenas faz correções

2022-09-26 19:59 UTC, dennervidal commented on package.json
> +    "git-dirty": "~1.0.2"
pode remover o git-dirty

2022-09-26 19:59 UTC, dennervidal commented on package.json
>    "dependencies": {
acho que faltou adicionar e remover algumas deps aqui, segue lista do trackd:

- "@typescript-eslint/eslint-plugin"
- "@typescript-eslint/parser"
- "eslint-config-prettier"
- "eslint-config-standard"
- "eslint-config-standard-with-typescript"
- "eslint-import-resolver-typescript"
- "eslint-plugin-import"
- "eslint-plugin-n"
- "eslint-plugin-node"
- "eslint-plugin-prettier"
- "eslint-plugin-promise"
- "eslint-plugin-react"
- "eslint-plugin-react-hooks"

2022-09-26 19:59 UTC, dennervidal commented on package.json
> +    "@babel/eslint-parser": "7.19.1",
não usa (pelo menos no eslint do trackd e no vendas não achei)

2022-09-26 19:59 UTC, dennervidal commented on package.json
> +    "eslint-config-airbnb": "19.0.4",
não usamos

2022-09-26 19:59 UTC, dennervidal commented on package.json
> +    "eslint-plugin-flowtype": "8.0.3",
não usamos

2022-09-26 19:59 UTC, dennervidal commented on package.json
> +    "eslint-plugin-jsx-a11y": "6.6.1",
não usamos

2022-09-26 19:59 UTC, dennervidal commented on package.json
> +    "eslint-plugin-no-inline-styles": "1.0.5",
não usamos

2022-09-26 21:17 UTC, dennervidal commented
lembrando da nossa conversa:
- pegar a ultima versão dos pacotes que iremos utilizar
- remover elementos que não serão utilizados

se possível vamos adotar `standard-version` para versionar, veja o repo do [trackd](https://github.com/tecsinapse/trackd-app) no readme e adicione a documentação

precisa ver se o prettier e o eslint são dependencias ou peer dependency

cc @lucaspr98 @guilhermebrrrs

2022-09-27 19:42 UTC, dennervidal requested changes
apenas mais dois itens e podemos fechar

aí é só versionar e publicar no npm

2022-09-27 19:42 UTC, dennervidal commented on package.json
> +    "@typescript-eslint/eslint-plugin": "~5.8.31",
acho que a versão aqui ta errada

https://www.npmjs.com/package/@typescript-eslint/eslint-plugin

2022-09-27 19:42 UTC, dennervidal commented on package.json
> +    "eslint-config-prettier": "~8.0.5",
também não é a última versão https://www.npmjs.com/package/eslint-config-prettier

2022-09-27 20:33 UTC, merged